# -*- coding: utf-8 -*-
"""CatBoost_유민지_최종본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12D1RRLXm54sOF90Jr14TNQnnBCd7Fiie
"""

# [EDA] → [Feature Selection] → [Class Weight] → [파라미터 튜닝 + K-Fold] → [최종 학습] → [성능 평가] → [모델 저장]

!pip uninstall -y catboost numpy

!pip uninstall catboost numpy -y
!pip install numpy==1.23.5
!pip install --no-binary :all: catboost

!pip install catboost
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import classification_report, roc_auc_score
from catboost import CatBoostClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os

# CSV 업로드 (Colab에서)
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)), encoding='latin1')

# 결측치 제거
df_cleaned = df.dropna().copy()

# 타겟 분리
target_col = 'iptv_yn'
y = df_cleaned[target_col]
X = df_cleaned.drop(columns=[target_col])

# 범주형 컬럼 수동 지정
categorical_cols = [
    'ContractPVCName', 'ResidenceBuildingTypeCode', 'Gender', 'ReAgreementYesNo',
    'TransferYesNo', 'WifiSubscriptionYesNo', 'SalesSmallYesNo', 'InternetProductName',
    'MaxGeneralConsultationCount', 'MaxQualityConsultationCount',
    'MaxTermConsultationCount', 'MaxSaleConsultationCount',
    'MaxFeeConsultationCount', 'MaxEtcConsultationCount', 'AgeGroup'
]
numerical_cols = [col for col in X.columns if col not in categorical_cols]

# Label Encoding (범주형)
X_cat = X[categorical_cols].copy()
for col in categorical_cols:
    le = LabelEncoder()
    X_cat[col] = le.fit_transform(X_cat[col].astype(str))

# Standard Scaling (수치형)
X_num = X[numerical_cols].copy()
scaler = StandardScaler()
X_num_scaled = pd.DataFrame(scaler.fit_transform(X_num), columns=numerical_cols)

# 병합
X_processed = pd.concat([X_cat, X_num_scaled], axis=1)

"""# Feature Selection (CatBoost 기반)"""

# Feature Selection
fs_model = CatBoostClassifier(verbose=0, random_state=42)
selector = SelectFromModel(fs_model, threshold="median")  # 또는 0.005 등
X_selected = selector.fit_transform(X_processed, y)

# 선택된 Feature 이름 확인
feature_names = X_processed.columns
selected_mask = selector.get_support()
selected_features = feature_names[selected_mask]

print(f"\n✅ 선택된 Feature 개수: {len(selected_features)}")
print("📋 선택된 Feature 목록:")
for col in selected_features:
    print("-", col)

# 선택된 Feature로 DataFrame 생성
X_selected_df = X_processed[selected_features]

#학습에 쓰인 X_selected 가 저장하도록 해야 함 (shap 분석)
# 텍스트 파일로 저장
with open("selected_features.txt", "w") as f:
    for col in selected_features:
        f.write(col + "\n")

# 또는 JSON으로 저장 (리스트 형태)
import json
with open("selected_features.json", "w") as f:
    json.dump(list(selected_features), f)

print("✅ 선택된 feature 목록 저장 완료 (selected_features.txt, .json)")

"""# Class Weight 조정"""

# weighted roc,  weighted f1

# 1. 타겟 라벨 인코딩
y = df_cleaned['iptv_yn'].map({'N': 0, 'Y': 1})

# 2. 클래스 비율 계산
count_0 = len(y[y == 0])
count_1 = len(y[y == 1])

# 3. 예외 처리 및 가중치 계산
if count_1 == 0:
    raise ValueError("타겟값 '1'이 존재하지 않습니다.")

class_weight_ratio = count_0 / count_1

# 4. 출력
print(f"⚖️ scale_pos_weight: {class_weight_ratio:.2f}")

"""# Optuna 기반 CatBoost 파라미터 튜닝"""

!pip install optuna

import optuna
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from catboost import CatBoostClassifier

def objective(trial):
    params = {
        'depth': trial.suggest_int('depth', 4, 6),  # [수정] 탐색 범위 축소
        'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.15),  # [수정] 좁은 범위
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 5.0),  # [수정] 탐색 공간 축소
        'scale_pos_weight': class_weight_ratio,
        'n_estimators': 200,  # ✅ [추가] 학습 반복 수 제한 (기존 default: 1000)
        'early_stopping_rounds': 20,  # ✅ [추가] validation에서 성능 개선 없으면 조기 종료
        'verbose': 0,
        'random_state': 42
    }

    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)  # ✅ [수정] fold 수 5 → 3으로 줄임
    auc_scores = []

    for train_idx, val_idx in skf.split(X_selected, y):
        X_train, X_val = X_selected[train_idx], X_selected[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = CatBoostClassifier(**params)
        model.fit(X_train, y_train, eval_set=(X_val, y_val))  # ✅ [수정] eval_set 필수 for early_stopping
        y_proba = model.predict_proba(X_val)[:, 1]

        auc = roc_auc_score(y_val, y_proba)
        auc_scores.append(auc)

    return np.mean(auc_scores)

# 🎯 Optuna 실행
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=600)  # 그대로 유지

# ✅ 최적 파라미터 저장
optuna_best_params = study.best_trial.params
optuna_best_params['scale_pos_weight'] = class_weight_ratio
optuna_best_params['verbose'] = 0
optuna_best_params['random_state'] = 42

print("\n🎯 Optuna 최적 파라미터:", optuna_best_params)
print("📈 최고 평균 AUC:", study.best_value)

import os
import joblib
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, f1_score

model_save_dir = "/content/trial_models"
os.makedirs(model_save_dir, exist_ok=True)

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, stratify=y, random_state=42
)

auc_scores = []
f1_scores = []
trial_logs = []

best_auc = 0
best_model_path = None

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):
    X_fold_train, X_fold_val = X_train[train_idx], X_train[val_idx]
    y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model = CatBoostClassifier(**optuna_best_params)
    model.fit(X_fold_train, y_fold_train)

    y_val_pred = model.predict(X_fold_val)
    y_val_proba = model.predict_proba(X_fold_val)[:, 1]

    auc = roc_auc_score(y_fold_val, y_val_proba)
    f1 = f1_score(y_fold_val, y_val_pred)

    auc_scores.append(auc)
    f1_scores.append(f1)

    model_path = os.path.join(model_save_dir, f"model_fold{fold+1}_auc{auc:.4f}.pkl")
    joblib.dump(model, model_path)

    trial_logs.append({
        'fold': fold + 1,
        'model_path': model_path,
        'auc': auc,
        'f1_score': f1
    })

    if auc > best_auc:
        best_auc = auc
        best_model_path = model_path

# 최고 성능 모델 복사
if best_model_path:
    os.rename(best_model_path, "best_model.pkl")
    print("🏆 최고 성능 모델 저장 완료 → best_model.pkl")

import pandas as pd

df_trials = pd.DataFrame(trial_logs)
df_trials.to_csv("optuna_trials_log.csv", index=False)

print("📄 Trial 로그 저장 완료 → optuna_trials_log.csv")

from sklearn.metrics import (
    classification_report, roc_auc_score, average_precision_score,
    accuracy_score
)
import pandas as pd

def evaluate_model(y_true, y_pred, y_proba):
    report_dict = classification_report(y_true, y_pred, output_dict=True)
    accuracy = accuracy_score(y_true, y_pred)
    roc_auc = roc_auc_score(y_true, y_proba)
    pr_auc = average_precision_score(y_true, y_proba)

    result = {
        "Accuracy": accuracy,
        "N Precision": report_dict["0"]["precision"],
        "N Recall": report_dict["0"]["recall"],
        "N F1-Score": report_dict["0"]["f1-score"],
        "Y Precision": report_dict["1"]["precision"],
        "Y Recall": report_dict["1"]["recall"],
        "Y F1-Score": report_dict["1"]["f1-score"],
        "Macro Avg Precision": report_dict["macro avg"]["precision"],
        "Macro Avg Recall": report_dict["macro avg"]["recall"],
        "Macro Avg F1": report_dict["macro avg"]["f1-score"],
        "Weighted Avg Precision": report_dict["weighted avg"]["precision"],
        "Weighted Avg Recall": report_dict["weighted avg"]["recall"],
        "Weighted Avg F1": report_dict["weighted avg"]["f1-score"],
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc
    }

    return pd.DataFrame([result])

print("\n📊 [K-Fold 평가 리포트]")

fold_reports = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):
    X_fold_train, X_fold_val = X_train[train_idx], X_train[val_idx]
    y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model = CatBoostClassifier(**optuna_best_params)
    model.fit(X_fold_train, y_fold_train)

    y_pred = model.predict(X_fold_val)
    y_proba = model.predict_proba(X_fold_val)[:, 1]

    report_df = evaluate_model(y_fold_val, y_pred, y_proba)
    report_df["Fold"] = fold + 1
    fold_reports.append(report_df)

# 결과 합치기 + 평균 추가
df_kfold_report = pd.concat(fold_reports, ignore_index=True)
mean_row = df_kfold_report.drop(columns=["Fold"]).mean(numeric_only=True)
mean_row["Fold"] = "Average"
df_kfold_report = pd.concat([df_kfold_report, pd.DataFrame([mean_row])], ignore_index=True)

# 출력
from IPython.display import display
print("\n✅ [K-Fold 전체 리포트]")
display(df_kfold_report.round(4))

print("\n🧪 [Test 데이터 평가]")

final_model = CatBoostClassifier(**optuna_best_params)
final_model.fit(X_train, y_train)

y_test_pred = final_model.predict(X_test)
y_test_proba = final_model.predict_proba(X_test)[:, 1]

df_test_report = evaluate_model(y_test, y_test_pred, y_test_proba)
df_test_report["Dataset"] = "Test"

# 출력
display(df_test_report.round(4))